// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import { type Infer as __Infer } from "spacetimedb";

// Import all reducer arg schemas
import InjectChallengeReducer from "../inject_challenge_reducer";
import RecordPredictionReducer from "../record_prediction_reducer";
import UpdateBotStateReducer from "../update_bot_state_reducer";

export type InjectChallengeParams = __Infer<typeof InjectChallengeReducer>;
export type RecordPredictionParams = __Infer<typeof RecordPredictionReducer>;
export type UpdateBotStateParams = __Infer<typeof UpdateBotStateReducer>;

