// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export const BotState = __t.object("BotState", {
  id: __t.u32(),
  x: __t.f32(),
  y: __t.f32(),
  z: __t.f32(),
  health: __t.f32(),
  biome: __t.string(),
  tick: __t.u32(),
});
export type BotState = __Infer<typeof BotState>;

export const Challenge = __t.object("Challenge", {
  id: __t.u32(),
  challengeType: __t.string(),
  triggered: __t.bool(),
});
export type Challenge = __Infer<typeof Challenge>;

export const PredictionError = __t.object("PredictionError", {
  id: __t.u32(),
  tick: __t.u32(),
  errorMagnitude: __t.f32(),
  px: __t.f32(),
  py: __t.f32(),
  pz: __t.f32(),
  ax: __t.f32(),
  ay: __t.f32(),
  az: __t.f32(),
});
export type PredictionError = __Infer<typeof PredictionError>;

